# Generated by Django 3.1.7 on 2021-03-30 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('breakfast', models.BooleanField(default=False)),
                ('healthy', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('exercise', models.BooleanField(default=False)),
                ('sleep', models.IntegerField(default=0)),
                ('clothes', models.CharField(default='Casual', max_length=15)),
                ('start', models.TimeField(default=datetime.datetime.now)),
                ('rules', models.BooleanField(default=False)),
                ('money', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
